/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package object_book.study

import java.time.LocalDateTime

class Invitation(val time: LocalDateTime)

class Ticket(val fee: Long)

class Bag(
    private var invitation: Invitation?,
    private var ticket: Ticket?,
    private var amount: Long
) {
    val hasTicket: Boolean
        get() = ticket != null

    val hasInvitation: Boolean
        get() = invitation != null

    fun setTicket(ticket: Ticket?) {
        this.ticket = ticket
    }

    fun minusAmount(amount: Long) {
        this.amount -= amount
    }

    fun plusAmount(amount: Long) {
        this.amount += amount
    }
}

class Audience(val bag: Bag)

class TicketOffice(
    private var amount: Long,
    private val tickets: MutableList<Ticket>
) {
    fun publishTicket(): Ticket {
        return tickets.removeFirst()
    }

    fun minusAmount(amount: Long) {
        this.amount -= amount
    }

    fun plusAmount(amount: Long) {
        this.amount += amount
    }
}

class TicketSeller(private val ticketOffice: TicketOffice) {
    fun sellTo(audience: Audience) {
        if (audience.bag.hasInvitation) {
            val ticket = ticketOffice.publishTicket()
            audience.bag.setTicket(ticket)
        } else {
            val ticket = ticketOffice.publishTicket()
            audience.bag.minusAmount(ticket.fee)
            ticketOffice.plusAmount(ticket.fee)
            audience.bag.setTicket(ticket)
        }
    }
}


class Theater(
    private val ticketSeller: TicketSeller
) {
    fun enter(audience: Audience) {
        ticketSeller.sellTo(audience)
    }
}